spring:
  redis:
    host: 127.0.0.1
    port: 6378
    timeout: 1000
    pool:
      command-timeout: 200000
      max-attempts: 5
      # 跨集群执行命令时要遵循的最大重定向数量
      max-redirects: 3
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 16
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    clusters:
      master:
        # 各 Redis 节点信息
        nodes: 127.0.0.1:6379,127.0.0.1:6378
        # 执行命令超时时间
        command-timeout: 15000
        # 重试次数
        max-attempts: 5
        # 跨集群执行命令时要遵循的最大重定向数量
        max-redirects: 3
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 16
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      bak:
        # 各 Redis 节点信息
        nodes: 192.168.117.135:6379,192.168.117.135:6380,192.168.117.136:7379,192.168.117.136:7380,192.168.117.137:8379,192.168.117.137:8380
        # 执行命令超时时间
        command-timeout: 15001
        # 重试次数
        max-attempts: 5
        # 跨集群执行命令时要遵循的最大重定向数量
        max-redirects: 3
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 16
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
